### ISSUE TITLE
Nightly VS binary missing extra files 

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#448]
This applied since last week 

Just noticed as was fixing up download pg script and it kept being 1.5mb

I just checked and even after update of PR Merge just now still an issue @dimitre

**Comment by danoli3** [comment]
```
Run ./scripts/vs/create_package.sh
  ./scripts/vs/create_package.sh
  shell: D:\a\_temp\setup-msys[2](https://github.com/openframeworks/projectGenerator/actions/runs/7210813452/job/19644792481#step:7:2)\msys2.CMD {0}
  env:
    BITS: 6[4](https://github.com/openframeworks/projectGenerator/actions/runs/7210813452/job/19644792481#step:7:4)
    MSYSTEM: MINGW64
  adding: projectGenerator.exe (deflated [5](https://github.com/openframeworks/projectGenerator/actions/runs/7210813452/job/19644792481#step:7:5)5%)
  adding: data/ (stored 0%)
  adding: data/.gitkeep (stored 0%)
  ```
