### ISSUE TITLE
Support Auto Download of Addons via script - the era of packageManagers 

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#479]
I forget this is not built into the project Generator already as I been using it for so long.

https://github.com/danoli3/ofxAddonScript

I suggest we add a new format in addons.make to follow this convention and is run via the projectGenerator and code implemented for this script within the projectGenerator in C++ 
```
"ofxAddonScript" "https://github.com/danoli3/ofxAddonScript.git" "78fd6f27cf82743644f0c12f926ae053a42a7aa3"
```

Modifications to addons.make would allow for such definitions 

```
ofxXmlSettings
ofxTexturePacker https://github.com/danoli3/ofxTexturePacker
ofxShapeBatchRenderer https://github.com/stfj/ofxShapeBatchRenderer 71c2144a501ac80682c81aa20d95d0f07c307453
ofxTextAnimation https://github.com/TetsuakiBaba/ofxTextAnimation master
```

**Comment by dimitre** [comment]
Hey @danoli3 is this a valid syntax for makefile? 
by the way I've been using a personal tool to make reproduceable recipes in projects, including local addons if needed (specific branch or commit)
```yml
# name: AV2023

ofpath: ../../..

addons:
- ofxNetwork
- ofxAssimpModelLoader
- ofxMicroUI
- ofxMicroUIMidiController
- ofxTools
- ofxScenes
- ofxSyphon
- ofxMidi

# platforms: ["osx"]
# templates: ["vscode"]
```

as projectgenerator "rewrites" addons.make and remove not found addons, I've found this is not reliable for reproducing projects.
